### PR TITLE
[Metrics] Merge `metric-main` into `main`

### PR DESCRIPTION
**Pull request by ncooke3**
### Context
- Merging the client metrics feature into `main` for next GDT release
- All commits were PRs that were reviewed and approved.
- When approved, I can rebase this branch on top of `main` to keep the commit history.

### Next PR
- Update `GoogleDataTransport.podspec` for 9.2.0 release

cc: @ryanwilson

### CODE REVIEW

**Review by chliangGoogle — APPROVED** [review]
Make sure to update the changelog, is there any public API change?

**Review by paulb777 — APPROVED** [review]
💯

**Comment by ncooke3** [comment]
> Make sure to update the changelog, is there any public API change?

No public API change. Only internal API changes so I will release this in a new minor.

**Comment by ncooke3** [comment]
Merged from command line:
```
git checkout main
git pull
git merge metrics-main
git push origin main
```

**Pull request merged**
