### PR TITLE
[visionOS] Fix visionOS build errors on Xcode 15.0 Beta 2

### PR DESCRIPTION
**Pull request by ryanwilson**

### CODE REVIEW

**Review by morganchen12 — APPROVED** [review]

**Review by ncooke3 — APPROVED** [review]

**Review by paulb777 — APPROVED** [review]

**Comment by ncooke3** [comment]
I kicked off a re-run of the pod lib lint tests. The failures looked like flakes–– will investigate more if they fail again.

**Comment by ncooke3** [comment]
Fixing locally...

**Comment by ncooke3** [comment]
@paulb777 @andrewheard –– the remaining CI failure look unrelated to this change. WDYT?

**Comment by paulb777** [comment]
Agreed, looks like a flake

**Comment by ncooke3** [comment]
> Agreed, looks like a flake

thanks 👍 

I just pushed a remaining commit for the changelog. This is ready for a final pass @paulb777 @andrewheard

**Review by paulb777 — APPROVED** [review]
LGTM on green

**Comment by andrewheard** [comment]
These are passing locally for me on Xcode 13.4.1. `GCDWebServer` fails to link on Xcode 14.3 for what seems like a (pre-existing) [known issue](https://stackoverflow.com/questions/75574268/missing-file-libarclite-iphoneos-a-xcode-14-3).

**Review by andrewheard — APPROVED** [review]

**Pull request merged**
